### ISSUE TITLE
Rechunker action hhd-dev/rechunk

### ISSUE THREAD

**Issue by vst-name** [ublue-os/image-template#64]
Does this action actually work?
i couldn't help but notice that all upstream repo's use Rechunk task in Justfile...
Should i just setup Rechunk myself or is there a working configuration?

Thanks!

B.t.w. - was there a new version of bootc? new linter behavior enforces composefs=true which broke my build, i was about to make a PR but didn't make it in time =)

**Comment by p5** [comment]
The action _should_ work.  We just use a Justfile since it's easier to run locally.

RE bootc lint - I've just committed a change to disable this command, so it shouldn't be a problem any more.

**Comment by vst-name** [comment]
Unfortunately, no. Since [hhd-dev/rechunk](https://github.com/hhd-dev/rechunk/blob/v1.1.2/action.yml)  uses sudo to create and mount the container - and podman by default uses different storage per-user
```
runs:
  using: 'composite'
  steps:
    - name: Mount Image
      id: mount
      shell: bash
      run: |
        CREF=$(sudo podman create ${{ inputs.ref }} bash)
        MOUNT=$(sudo podman mount $CREF)
        echo "container=$CREF" >> $GITHUB_OUTPUT
        echo "mount=$MOUNT" >> $GITHUB_OUTPUT
```
And so the ublue justfile contains this snippet
```
    # Load into Rootful Podman
    ID=$(${SUDOIF} ${PODMAN} images --filter reference=localhost/"${image_name}":"${tag}" --format "'{{ '{{.ID}}' }}'")
    if [[ -z "$ID" && ! ${PODMAN} =~ docker ]]; then
        COPYTMP=$(mktemp -p "${PWD}" -d -t podman_scp.XXXXXXXXXX)
        ${SUDOIF} TMPDIR=${COPYTMP} ${PODMAN} image scp ${UID}@localhost::localhost/"${image_name}":"${tag}" root@localhost::localhost/"${image_name}":"${tag}"
        rm -rf "${COPYTMP}"
    fi
```

Perhaps the solution would be to change storage and state of podman to unified directories, so that users would be able to share storage?

**Comment by vst-name** [comment]
> Perhaps the solution would be to change storage and state of podman to the same unified directory, so that "users" would be able to share storage?

Nope, root created objects are inaccessible to other users, what a pain...

**Comment by JianZcar** [comment]
> When I try to run rechunk I just get:
> 
> ```
> Trying to pull localhost/lavender-linux-devel:latest...
> time="2025-04-14T11:32:26Z" level=warning msg="Failed, retrying in 1s ... (1/3). Error: initializing source docker://localhost/lavender-linux-devel:latest: pinging container registry localhost: Get \"https://localhost/v2/\": dial tcp [::1]:443: connect: connection refused"
> time="2025-04-14T11:32:27Z" level=warning msg="Failed, retrying in 1s ... (2/3). Error: initializing source docker://localhost/lavender-linux-devel:latest: pinging container registry localhost: Get \"https://localhost/v2/\": dial tcp [::1]:443: connect: connection refused"
> time="2025-04-14T11:32:28Z" level=warning msg="Failed, retrying in 1s ... (3/3). Error: initializing source docker://localhost/lavender-linux-devel:latest: pinging container registry localhost: Get \"https://localhost/v2/\": dial tcp [::1]:443: connect: connection refused"
> Error: initializing source docker://localhost/lavender-linux-devel:latest: pinging container registry localhost: Get "https://localhost/v2/": dial tcp [::1]:443: connect: connection refused
> Error: Process completed with exit code 125.
> ```
> 
> for some reason, it can't connect to localhost

I have a solution for the pulling problem but i still can't make it work properly, can i make a pull request?

**Comment by JianZcar** [comment]
i have made a pull request but i still cant quite manage to get it fully working on my custom image, it pulls but i get this error

```
Failed to set capabilities on file 'setcap': No such file or directory
Failed to set capabilities on file 'setcap': No such file or directory
Failed to set capabilities on file 'setcap': No such file or directory
Failed to set capabilities on file 'setcap': No such file or directory
Failed to set capabilities on file 'setcap': No such file or directory
Failed to set capabilities on file 'setcap': No such file or directory
Failed to set capabilities on file 'setcap': No such file or directory
Failed to set capabilities on file 'setcap': No such file or directory
Detected Fedora version 41 or higher.
Setting latest capabilities on sssd binaries.
Failed to set capabilities on file 'setcap': No such file or directory
Failed to set capabilities on file 'setcap': No such file or directory
Failed to set capabilities on file 'setcap': No such file or directory
Failed to set capabilities on file 'setcap': No such file or directory
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Polkitd group not found. Polkits will not work
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Committing to OSTree

Initializing OSTree repo

Creating repo with ref master
error: No such file or directory: /usr/lib/modules
Error: Process completed with exit code 1.
```

**Comment by vst-name** [comment]
FYI, rechunker expects the image to be in root-store, as the GH actions start's it as root user

So, this works - https://github.com/vst-name/ublue-aurora-dx/blob/main/.github/workflows/build.yml

**Comment by JianZcar** [comment]
ohh so the build step was the problem?

**Comment by vst-name** [comment]
@castrojo

Hi! Can you look into that please?
I may as well just PR-in [this](https://github.com/vst-name/ublue-aurora-dx/blob/main/.github/workflows/build.yml#L105) section

**Comment by vst-name** [comment]
Hmmm, there is an interesting new addition to the build in the repo
```
      - name: Mount BTRFS for podman storage
        uses: ublue-os/container-storage-action@main
```
https://github.com/ublue-os/container-storage-action/blob/main/mount_btrfs.sh
It seems to solve the store problem...
